/*
    DO NOT EDIT THIS FILE DIRECTLY
    This file was generated by a script in FMOD Studio 
*/

package;

class FmodSongs {
    public static inline var Game:String = "event:/Music/Game";
    public static inline var LetsGo:String = "event:/Music/LetsGo";
    public static inline var Title:String = "event:/Music/Title";
    public static inline var Title2:String = "event:/Music/Title2";
}

class FmodSFX {
    public static inline var BoatEngine:String = "event:/SFX/Boat/BoatEngine";
    public static inline var MenuHover:String = "event:/SFX/Menu/MenuHover";
    public static inline var MenuSelect:String = "event:/SFX/Menu/MenuSelect";
}
